name: Coverage
on:
  push:
    branches: 
      - master
      
jobs: 
  build-and-test: 
    runs-on: ubuntu-latest
    steps:     
    - name: Upload coverage to Codecov 
    - uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}  
        file: ./coverage/lcov.info
